### ISSUE TITLE
Not recognizing session

### ISSUE THREAD

**Issue by razielaka** [Visual-Brahma/trackit#16]
Sometimes after a session, the trackit page pops up but it doesn't show the session details. It says you're up to date or something along those lines. I have to refresh to make it show the details. Sometimes refreshing doesn't do anything and the session details are lost and they aren't shown on the reports page either.

![image](https://github.com/Visual-Brahma/trackit/assets/9019679/d7ff5dbc-7da3-4d84-abd7-3d2a9bdbc84c)

**Comment by blaze2004** [comment]
It could be due to delay in writing the data to localstorage by the extension, probably setting a timeout of 1s before reading localstorage will fix it.

**Comment by blaze2004** [comment]
Its fixed in [7199d70](https://github.com/Visual-Brahma/trackit/commit/7199d704b6e45995edf88e248695ab87d8738f72).

Let me know if it happens again.
